apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque-service
  namespace: sre-platform
  labels:
    app: estoque-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estoque-service
  template:
    metadata:
      labels:
        app: estoque-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: estoque-service
          image: lucasferreiradealmeida/estoque-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: NOTIFICACAO_SERVICE_URL
              value: "http://notificacao-service:8000"
            - name: ESTOQUE_MINIMO
              value: "10"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
