apiVersion: v1
kind: Service
metadata:
  name: estoque-service
  namespace: sre-platform
  labels:
    app: estoque-service
spec:
  selector:
    app: estoque-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
