apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacao-service
  namespace: sre-platform
  labels:
    app: notificacao-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificacao-service
  template:
    metadata:
      labels:
        app: notificacao-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: notificacao-service
          image: lucasferreiradealmeida/notificacao-service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
